### ISSUE TITLE
ImportError: cannot import name 'ols'

### ISSUE THREAD

**Issue by albanywang2016** [cuemacro/finmarketpy#14]
i got error "ImportError: cannot import name 'ols'"
 what am i missing?

Traceback (most recent call last):
  File "C:/Users/lei.wang/AppData/Local/Continuum/Anaconda3/Lib/site-packages/finmarketpy_examples/backtest_example.py", line 30, in <module>
    from finmarketpy.backtest import BacktestRequest, Backtest
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\finmarketpy\__init__.py", line 1, in <module>
    from finmarketpy import (backtest, economics, util)
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\finmarketpy\backtest\__init__.py", line 3, in <module>
    from finmarketpy.backtest.backtestengine import Backtest
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\finmarketpy\backtest\backtestengine.py", line 17, in <module>
    from findatapy.util import LoggerManager
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\findatapy\__init__.py", line 3, in <module>
    from findatapy import (market, timeseries, util)
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\findatapy\market\__init__.py", line 8, in <module>
    from findatapy.market.market import Market, FXVolFactory, FXCrossFactory, FXConv
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\findatapy\market\market.py", line 461, in <module>
    from findatapy.timeseries import Calculations, Filter, Timezone
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\findatapy\timeseries\__init__.py", line 6, in <module>
    from findatapy.timeseries.calculations import Calculations
  File "C:\Users\lei.wang\AppData\Local\Programs\Python\Python36-32\lib\site-packages\findatapy\timeseries\calculations.py", line 23, in <module>
    from pandas.stats.api import ols
ImportError: cannot import name 'ols'

**Comment by saeedamen** [comment]
Hi @albanywang2016 - I think the ols package might be deprecated in newer versions of pandas (also I haven't tried the libraries in Python 3.6, I generally use 3.5). The nearest alternative is statsmodels which uses ols. As a temporary fix I've it to import the statsmodels OLS module, so it should at least run (but don't think the regression functions will work - need to rewrite my code to use statsmodels OLS). You'll need to update the findatapy library on your system. Hopefully it'll work, if not, let me know.
